// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [ 
    {
      type: 'category',
      label: 'Introduction',
      items: [
        {
          type: 'autogenerated',
          dirName: 'introduction', // Generate sidebar slice from docs/api
        }
      ],
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        {
          type: 'autogenerated',
          dirName: 'components', // Generate sidebar slice from docs/api
        }
      ],
    },
    {
      type: 'category',
      label: 'Framework Integrations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'framework-integration', // Generate sidebar slice from docs/api
        }
      ],
    },
    {
      type: 'category',
      label: 'Static Site Generation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'static-site-generation', // Generate sidebar slice from docs/api
        }
      ],
    },
    {
      type: 'category',
      label: 'Config',
      items: [
        {
          type: 'autogenerated',
          dirName: 'config', // Generate sidebar slice from docs/api
        }
      ],
    },
    {
      type: 'category',
      label: 'Output Targets',
      items: [
        {
          type: 'autogenerated',
          dirName: 'output-targets', // Generate sidebar slice from docs/api
        }
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides', // Generate sidebar slice from docs/api
        }
      ],
    },
    {
      type: 'category',
      label: 'Testing',
      items: [
        {
          type: 'autogenerated',
          dirName: 'testing', // Generate sidebar slice from docs/api
        }
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides', // Generate sidebar slice from docs/api
        }
      ],
    },
    {
      type: 'category',
      label: 'Core',
      items: [
        {
          type: 'autogenerated',
          dirName: 'core', // Generate sidebar slice from docs/api
        }
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides', // Generate sidebar slice from docs/api
        }
      ],
    },
    {
      type: 'category',
      label: 'Community',
      items: [
        {
          type: 'link',
          label: 'Stencil on Twitter',
          href: 'https://twitter.com/stenciljs',
        },
        {
          type: 'link',
          label: 'Stencil on Slack',
          href: 'https://stencil-worldwide.herokuapp.com/',
        },
        {
          type: 'link',
          label: 'Stencil on GitHub',
          href: 'https://github.com/ionic-team/stencil',
        },
      ],
    },
    {
      type: 'category',
      label: 'Legal',
      items: [
        'telemetry',
        {
          type: 'link',
          label: 'Privacy Policy',
          href: 'https://ionic.io/privacy',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference', // Generate sidebar slice from docs/api
        }
      ],
    },
  ],
};

module.exports = sidebars;
